version: '3.8'

# Development version with hot reload
services:
  # Backend service - development mode
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shipsradar-backend-dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - API_HOST=0.0.0.0
      - API_PORT=8000
    env_file:
      - ./backend/.env
    volumes:
      # Mount entire backend for hot reload
      - ./backend:/app:delegated
      - /app/__pycache__
      - /app/.venv
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    networks:
      - shipsradar-network

  # Frontend service - development mode
  frontend-dev:
    image: node:18-alpine
    container_name: shipsradar-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - shipsradar-network

networks:
  shipsradar-network:
    driver: bridge
    name: shipsradar-network-dev

